---
title: "ET"
author: "Tiffany Le"
date: "2026-05-05"
output: pdf_document
---
```{r, message = F, warning = F}
library(tidyverse)
library(lubridate)
library(stringr)
library(fs)
library(changepoint)
```

```{r}
et_join <- function(product, folder = "../Data/ET") {
  files <- dir_ls(folder, regexp = product)
  et <- map_dfr(files, function(f) {
    name <- path_file(f)
    site   <- str_extract(name, "(?<=ET_).+(?=buffer)")
    buffer   <- str_extract(name, "(?<=buffer)[0-9]+") |> as.numeric()
    data <- read_csv(f, show_col_types = FALSE)
    data |> 
      mutate(
        Site = site,
        Buffer = buffer,
        Source = name
      )
  })
  et
}
```

```{r}
modis <- et_join("MODIS")
openet <- et_join("OpenET")
pml <- et_join("PML")
```

```{r}
labels <- c("Cool-Season Recharge", "Pre-Monsoon Dry", "Monsoon", "Post-Monsoon Recession")
cameras <- data.frame(Site = c("Boquillas", "CharlestonMesquite", "Contention", "Fairbank", "Hereford", "Hunter", "Moson", "St.David"), Camera = c(8, 2, 6, 1, 5, 4, 3, 7))
modis <- left_join(modis, cameras, by = "Site")
modis$Date <- as.Date(modis$Date)
openet <- left_join(openet, cameras, by = "Site")
openet$Date <- as.Date(openet$Date)
pml <- left_join(pml, cameras, by = "Site")
pml$Date <- as.Date(pml$Date)
```

```{r}
modis <- modis %>% arrange(Date, Buffer, Camera)
modis$Site <- as.factor(modis$Site)
openet <- openet %>% arrange(Date, Buffer, Camera)
openet$Site <- as.factor(openet$Site)
pml <- pml %>% arrange(Date, Buffer, Camera)
pml$Site <- as.factor(pml$Site)
```

```{r, message = FALSE}
camera_filter <- c(1, 2, 6, 7)

water_year <- function(date) {
  y <- as.numeric(format(date, "%Y"))
  m <- as.numeric(format(date, "%m"))
  ifelse(m >= 10, y + 1, y)
}

season <- function(month) {
  if (month %in% c(12, 1, 2, 3)) return(1)
  else if (month %in% c(4, 5, 6)) return(2)
  else if (month %in% c(7, 8, 9)) return(3)
  else if (month %in% c(10, 11)) return(4)
}

modis$WY <- water_year(modis$Date)
modis$Season <- sapply(as.integer(format(modis$Date, "%m")), season)

seasonal_modis <- modis %>%
  filter(Camera %in% camera_filter) %>%
  group_by(WY, Season) %>%
  summarise(across(ET, ~ sum(.x, na.rm = TRUE)))

openet$WY <- water_year(openet$Date)
openet$Season <- sapply(as.integer(format(openet$Date, "%m")), season)

seasonal_openet <- openet %>%
  filter(Camera %in% camera_filter) %>%
  group_by(WY, Season) %>%
  summarise(across(ET, ~ sum(.x, na.rm = TRUE)))

pml$WY <- water_year(pml$Date)
pml$Season <- sapply(as.integer(format(pml$Date, "%m")), season)

seasonal_pml <- pml %>%
  filter(Camera %in% camera_filter) %>%
  group_by(WY, Season) %>%
  summarise(across(ET, ~ sum(.x, na.rm = TRUE)))
```

```{r}
plot(ET ~ as.factor(Buffer), data = modis)
```

```{r}
plot(ET ~ as.factor(Buffer), data = openet)
```

```{r}
plot(ET ~ as.factor(Buffer), data = pml)
```

```{r}
plot(ET ~ Site, data = modis)
```

```{r}
plot(ET ~ Site, data = openet)
```

```{r}
plot(ET ~ Site, data = pml)
```

```{r, message = F, warning = F}
modis %>%
  ggplot(aes(x = Buffer, y = ET)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE, color = "blue") +
  facet_wrap(~ Site, scales = "free_y") +
  labs(
    title = "MODIS ET vs Buffer Distance",
    x = "Buffer Distance (m)",
    y = "ET (mm)"
  ) +
  theme_classic()
```

```{r, message = F, warning = F}
openet %>%
  ggplot(aes(x = Buffer, y = ET)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE, color = "blue") +
  facet_wrap(~ Site, scales = "free_y") +
  labs(
    title = "OpenET ET vs Buffer Distance",
    x = "Buffer Distance (m)",
    y = "ET (mm)"
  ) +
  theme_classic()
```

```{r, message = F, warning = F}
pml %>%
  ggplot(aes(x = Buffer, y = ET)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE, color = "blue") +
  facet_wrap(~ Site, scales = "free_y") +
  labs(
    title = "PML ET vs Buffer Distance",
    x = "Buffer Distance (m)",
    y = "ET (mm)"
  ) +
  theme_classic()
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_modis[seasonal_modis$Season == s,]
  matrix <- cbind(subset$ET, 1, subset$WY)
  cp_reg <- cpt.reg(matrix, method = "PELT")
  segments <- c(0, cpts(cp_reg), nrow(subset))
  params <- param.est(cp_reg)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  colors <- rainbow(length(segments) - 1)
  for (i in 1:length(colors)) {
    idx <- (segments[i] + 1):segments[i + 1]
    intercept <- params$beta[i, 1]
    slope <- params$beta[i, 2]
    fitted <- intercept + slope * subset$WY[idx]
    lines(subset$WY[idx], fitted, col = colors[i], lwd = 2)
  }
}
mtext("Seasonal ET Regression Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_openet[seasonal_openet$Season == s,]
  matrix <- cbind(subset$ET, 1, subset$WY)
  cp_reg <- cpt.reg(matrix, method = "PELT")
  segments <- c(0, cpts(cp_reg), nrow(subset))
  params <- param.est(cp_reg)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  colors <- rainbow(length(segments) - 1)
  for (i in 1:length(colors)) {
    idx <- (segments[i] + 1):segments[i + 1]
    intercept <- params$beta[i, 1]
    slope <- params$beta[i, 2]
    fitted <- intercept + slope * subset$WY[idx]
    lines(subset$WY[idx], fitted, col = colors[i], lwd = 2)
  }
}
mtext("Seasonal ET Regression Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_pml[seasonal_pml$Season == s,]
  matrix <- cbind(subset$ET, 1, subset$WY)
  cp_reg <- cpt.reg(matrix, method = "PELT")
  segments <- c(0, cpts(cp_reg), nrow(subset))
  params <- param.est(cp_reg)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  colors <- rainbow(length(segments) - 1)
  for (i in 1:length(colors)) {
    idx <- (segments[i] + 1):segments[i + 1]
    intercept <- params$beta[i, 1]
    slope <- params$beta[i, 2]
    fitted <- intercept + slope * subset$WY[idx]
    lines(subset$WY[idx], fitted, col = colors[i], lwd = 2)
  }
}
mtext("Seasonal ET Regression Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_modis[seasonal_modis$Season == s,]
  cp_mean <- cpt.mean(subset$ET, method = "PELT", minseglen = 10)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  years <- subset$WY[cpts(cp_mean)]
  segments <- c(0, cpts(cp_mean), nrow(subset))
  means <- sapply(1:(length(segments) - 1), function(i) {
    start <- segments[i] + 1
    end <- segments[i + 1]
    mean(subset$ET[start:end])
  })
  sp <- data.frame(
    x = subset$WY[head(segments, -1) + 1],
    xend = subset$WY[tail(segments, -1)],
    y = means,
    yend = means
  )
  segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
}
mtext("Seasonal ET Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_openet[seasonal_openet$Season == s,]
  cp_mean <- cpt.mean(subset$ET, method = "PELT", minseglen = 10)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  years <- subset$WY[cpts(cp_mean)]
  segments <- c(0, cpts(cp_mean), nrow(subset))
  means <- sapply(1:(length(segments) - 1), function(i) {
    start <- segments[i] + 1
    end <- segments[i + 1]
    mean(subset$ET[start:end])
  })
  sp <- data.frame(
    x = subset$WY[head(segments, -1) + 1],
    xend = subset$WY[tail(segments, -1)],
    y = means,
    yend = means
  )
  segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
}
mtext("Seasonal ET Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_pml[seasonal_pml$Season == s,]
  cp_mean <- cpt.mean(subset$ET, method = "PELT", minseglen = 10)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  years <- subset$WY[cpts(cp_mean)]
  segments <- c(0, cpts(cp_mean), nrow(subset))
  means <- sapply(1:(length(segments) - 1), function(i) {
    start <- segments[i] + 1
    end <- segments[i + 1]
    mean(subset$ET[start:end])
  })
  sp <- data.frame(
    x = subset$WY[head(segments, -1) + 1],
    xend = subset$WY[tail(segments, -1)],
    y = means,
    yend = means
  )
  segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
}
mtext("Seasonal ET Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_modis[seasonal_modis$Season == s, ]
  cp_var <- cpt.var(subset$ET, method = "PELT", penalty = "AIC")
  segments <- c(1, cpts(cp_var) + 1, nrow(subset) + 1)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  for (i in 1:(length(segments) - 1)) {
    j <- segments[i]:(segments[i + 1] - 1)
    left  <- subset$WY[segments[i]]
    right <- subset$WY[segments[i + 1] - 1]
    sm <- mean(subset$ET[j])
    ssd   <- sd(subset$ET[j])
    bottom <- sm - ssd
    top    <- sm + ssd
    rect(left, bottom,
         right, top,
         col = adjustcolor("skyblue", alpha.f = 0.3),
         border = NA)
  }
}
mtext("Seasonal ET Variance Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_openet[seasonal_openet$Season == s, ]
  cp_var <- cpt.var(subset$ET, method = "PELT", penalty = "AIC")
  segments <- c(1, cpts(cp_var) + 1, nrow(subset) + 1)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  for (i in 1:(length(segments) - 1)) {
    j <- segments[i]:(segments[i + 1] - 1)
    left  <- subset$WY[segments[i]]
    right <- subset$WY[segments[i + 1] - 1]
    sm <- mean(subset$ET[j])
    ssd   <- sd(subset$ET[j])
    bottom <- sm - ssd
    top    <- sm + ssd
    rect(left, bottom,
         right, top,
         col = adjustcolor("skyblue", alpha.f = 0.3),
         border = NA)
  }
}
mtext("Seasonal ET Variance Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_pml[seasonal_pml$Season == s, ]
  cp_var <- cpt.var(subset$ET, method = "PELT", penalty = "AIC")
  segments <- c(1, cpts(cp_var) + 1, nrow(subset) + 1)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  for (i in 1:(length(segments) - 1)) {
    j <- segments[i]:(segments[i + 1] - 1)
    left  <- subset$WY[segments[i]]
    right <- subset$WY[segments[i + 1] - 1]
    sm <- mean(subset$ET[j])
    ssd   <- sd(subset$ET[j])
    bottom <- sm - ssd
    top    <- sm + ssd
    rect(left, bottom,
         right, top,
         col = adjustcolor("skyblue", alpha.f = 0.3),
         border = NA)
  }
}
mtext("Seasonal ET Variance Change Points", side = 3, outer = TRUE)
```

```{r}
flow <- read.csv("../Data/USPPFlowMonitoring2006_2025.csv")
flow$FP <- flow$Flow.Code
flow$FP[flow$FP == 2] <- 1
flow <- flow[flow$FP %in% c(0, 1),]
flow$Date <- as.Date(flow$Date)
flow <- left_join(flow, cameras, by = "Site")
flow$WY <- water_year(flow$Date)
flow$Season <- sapply(as.integer(format(flow$Date, "%m")), season)
reach <- flow[flow$Camera %in% camera_filter,]
reach <- aggregate(FP ~ WY + Season, data = reach, FUN = mean)
flow_modis <- left_join(reach, seasonal_modis, by = c("WY", "Season"))
```

```{r}
modis_mod <- lm(FP ~ ET, data = flow_modis[flow_modis$Season == 3,])
summary(modis_mod)
```

```{r}
plot(FP ~ ET, data = flow_modis[flow_modis$Season == 3,])
abline(modis_mod)
```

Estimated coefficient is opposite of expected.

```{r}
s2 <- flow_modis[flow_modis$Season == 2, c("WY", "ET")]
s3 <- flow_modis[flow_modis$Season == 3, c("WY", "FP")]
lagged <- left_join(s3, s2, by = "WY")

lagged_mod <- lm(FP ~ ET, data = lagged)
summary(lagged_mod)
```

Lagging by an additional year decreases the coefficient estimate. The estimate is not statistically significant but there's still a negative relationship.

```{r}
plot(FP ~ ET, xlab = "ET (mm)", ylab = "Mean FP", main =  "Mean Monsoon Season FP vs. Pre-Monsoon Dry Season ET", pch = 19, font.main = 1, data = lagged)
abline(lagged_mod, col = "red")
```

Every additional 1,000 mm of ET in the antecedent pre-monsoon dry season decreases FP by 6.874%.

```{r}
daymet <- read.csv("../Data/Daymet2006_2024.csv")
daymet$date <- as.Date(daymet$date)
daymet$WY <- water_year(daymet$date)
daymet$Season <- sapply(as.integer(format(daymet$date, "%m")), season)
daymet$temp <- (daymet$tmax + daymet$tmin) / 2
daymet <- daymet[daymet$camera %in% c(1, 2, 6, 7),]

seasonal <- daymet %>%
  group_by(WY, Season) %>%
  summarise(
    precip = sum(prcp, na.rm = TRUE),
    vpd = mean(tvpd, na.rm = TRUE),
    temp = mean(temp, na.rm = TRUE),
    .groups = "drop"
)

seasonal_flow <- left_join(reach, seasonal, by = c("WY", "Season"))
all <- left_join(seasonal_flow, seasonal_modis, by = c("WY", "Season"))
all_lagged <- left_join(lagged, all[all$Season == 3, c("WY", "precip", "vpd", "temp")], by = "WY")
```

```{r}
all_mod <- lm(FP ~ ET + precip + temp, data = all_lagged)
summary(all_mod)
```

```{r}
vpd_mod <- lm(FP ~ vpd + precip + temp, data = all_lagged)
summary(vpd_mod)
```

ET and VPD are multicollinear, can't distinguish effects of each.

```{r}
cor(all_lagged$ET, all_lagged$vpd, use = "complete.obs")
```

```{r}
cor(all_lagged[, -1], use = "complete.obs")
```

```{r}
subset <- seasonal_modis[seasonal_modis$Season == 2,]
cp_mean <- cpt.mean(subset$ET, method = "PELT", minseglen = 10)
plot(subset$WY, subset$ET,
     pch = 19, col = "black",
     xlab = "", ylab = "ET (mm)", main = "Pre-Monsoon Dry Season ET Change-Points", font.main = 1)
years <- subset$WY[cpts(cp_mean)]
segments <- c(0, cpts(cp_mean), nrow(subset))
means <- sapply(1:(length(segments) - 1), function(i) {
  start <- segments[i] + 1
  end <- segments[i + 1]
  mean(subset$ET[start:end])
})
sp <- data.frame(
  x = subset$WY[head(segments, -1) + 1],
  xend = subset$WY[tail(segments, -1)],
  y = means,
  yend = means
)
segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
```

```{r}
points <- read.csv("../Data/pts_for_Jawad.csv")[1:8,]
points$Name <- gsub(" Camera", "", points$Name, ignore.case = TRUE)
points$Index <- 1:8
```

```{r}
jawad <- do.call(rbind, lapply(seq_along(points$Index), function(k) {
  i  <- points$Index[k]
  n <- points$Name[k]
  
  file <- paste0("../Data/Jawad_ET/J", i, ".csv")
  
  df <- read.csv(file)
  df$Site <- n
  df
}))

jawad <- left_join(jawad, cameras, by = "Site")
jawad$date <- as.Date(jawad$date)
jawad$ET <- jawad$LE_model * 0.0353
jawad <- arrange(jawad, date, Camera)
```

```{r, message = FALSE}
jawad$WY <- water_year(jawad$date)
jawad$Season <- sapply(as.integer(format(jawad$date, "%m")), season)

seasonal_jawad <- jawad %>%
  filter(Camera %in% camera_filter) %>%
  group_by(WY, Season) %>%
  summarise(across(ET, ~ sum(.x, na.rm = TRUE)))
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_jawad[seasonal_jawad$Season == s,]
  matrix <- cbind(subset$ET, 1, subset$WY)
  cp_reg <- cpt.reg(matrix, method = "PELT")
  segments <- c(0, cpts(cp_reg), nrow(subset))
  params <- param.est(cp_reg)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  colors <- rainbow(length(segments) - 1)
  for (i in 1:length(colors)) {
    idx <- (segments[i] + 1):segments[i + 1]
    intercept <- params$beta[i, 1]
    slope <- params$beta[i, 2]
    fitted <- intercept + slope * subset$WY[idx]
    lines(subset$WY[idx], fitted, col = colors[i], lwd = 2)
  }
}
mtext("Seasonal ET Regression Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_jawad[seasonal_jawad$Season == s,]
  cp_mean <- cpt.mean(subset$ET, method = "PELT", minseglen = 8)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  years <- subset$WY[cpts(cp_mean)]
  segments <- c(0, cpts(cp_mean), nrow(subset))
  means <- sapply(1:(length(segments) - 1), function(i) {
    start <- segments[i] + 1
    end <- segments[i + 1]
    mean(subset$ET[start:end])
  })
  sp <- data.frame(
    x = subset$WY[head(segments, -1) + 1],
    xend = subset$WY[tail(segments, -1)],
    y = means,
    yend = means
  )
  segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
}
mtext("Seasonal ET Change Points", side = 3, outer = TRUE)
```

```{r}
par(mfrow = c(2, 2), mar = c(3, 4, 2, 1), oma = c(0, 0, 3, 0))
for (s in 1:4) {
  subset <- seasonal_jawad[seasonal_jawad$Season == s, ]
  cp_var <- cpt.var(subset$ET, method = "PELT", penalty = "AIC")
  segments <- c(1, cpts(cp_var) + 1, nrow(subset) + 1)
  plot(subset$WY, subset$ET,
       pch = 19, col = "black",
       xlab = "", ylab = "ET (mm)", main = labels[s], font.main = 1)
  for (i in 1:(length(segments) - 1)) {
    j <- segments[i]:(segments[i + 1] - 1)
    left  <- subset$WY[segments[i]]
    right <- subset$WY[segments[i + 1] - 1]
    sm <- mean(subset$ET[j])
    ssd   <- sd(subset$ET[j])
    bottom <- sm - ssd
    top    <- sm + ssd
    rect(left, bottom,
         right, top,
         col = adjustcolor("skyblue", alpha.f = 0.3),
         border = NA)
  }
}
mtext("Seasonal ET Variance Change Points", side = 3, outer = TRUE)
```

```{r}
flow_jawad <- left_join(reach, seasonal_jawad, by = c("WY", "Season"))
s2 <- flow_jawad[flow_jawad$Season == 2, c("WY", "ET")]
s3 <- flow_jawad[flow_jawad$Season == 3, c("WY", "FP")]
lagged_jawad <- left_join(s3, s2, by = "WY")

all_jawad <- left_join(seasonal_flow, seasonal_jawad, by = c("WY", "Season"))
all_lagged_jawad <- left_join(lagged_jawad, all_jawad[all_jawad$Season == 3, c("WY", "precip", "vpd", "temp")], by = "WY")
```

```{r}
jawad_mod <- lm(FP ~ ET, data = lagged_jawad)
summary(jawad_mod)
```

```{r}
plot(FP ~ ET, data = lagged_jawad)
abline(jawad_mod)
```

```{r}
all_jawad_mod <- lm(FP ~ ET + precip + vpd + temp, data = all_lagged_jawad)
summary(all_jawad_mod)
```
