---
title: "Exhaustive Hydroclimatic CPD"
author: "Tiffany Le"
date: "2026-06-07"
output: pdf_document
---

```{r setup, warning = F, message = F}
library(dplyr)
library(changepoint)

water_year <- function(date) {
  y <- as.numeric(format(date, "%Y"))
  m <- as.numeric(format(date, "%m"))
  ifelse(m >= 10, y + 1, y)
}

season <- function(month) {
  if (month %in% c(12, 1, 2, 3)) return(1)
  else if (month %in% c(4, 5, 6)) return(2)
  else if (month %in% c(7, 8, 9)) return(3)
  else if (month %in% c(10, 11)) return(4)
}

labels <- c("CSR", "PMD", "MON", "PMR")

cameras <- data.frame(
  Site = c(
    "Boquillas",
    "CharlestonMesquite",
    "Contention",
    "Fairbank",
    "Hereford",
    "Hunter",
    "Moson",
    "St.David"
  ),
  Camera = c(8, 2, 6, 1, 5, 4, 3, 7)
)
```

```{r flow, warning = F, message = F}
flow <- read.csv("../Data/USPPFlowMonitoring2006_2025.csv", stringsAsFactors = F)
flow$Flow.Code[flow$Flow.Code == 2] <- 1
flow <- flow[flow$Flow.Code %in% c(0, 1), ]
flow$Date <- as.Date(flow$Date)
flow <- merge(flow, cameras, by = "Site")
flow$WY <- water_year(flow$Date)
flow$Season <- sapply(as.integer(format(flow$Date, "%m")), season)
seasonal_fp <- flow %>%
  group_by(Camera, WY, Season) %>%
  summarise(FP = mean(Flow.Code, na.rm = T), .groups = "drop")
```

```{r climate, warning = F, message = F}
daymet <- read.csv("../Data/Daymet2006_2024.csv")
daymet$date <- as.Date(daymet$date)
daymet$wy <- water_year(daymet$date)
daymet$season <- sapply(as.integer(format(daymet$date, "%m")), season)
daymet$temp <- (daymet$tmax + daymet$tmin) / 2
seasonal_daymet <- daymet %>%
  group_by(camera, wy, season) %>%
  summarise(
    precip = sum(prcp, na.rm = T),
    vpd = mean(tvpd, na.rm = T),
    temp = mean(temp, na.rm = T),
    .groups = "drop"
  )

seasonal_hydro <- seasonal_daymet %>%
  rename(Camera = camera, WY = wy, Season = season) %>%
  left_join(seasonal_fp, by = c("Camera", "WY", "Season"))
```

```{r function, warning = F, message = F}
plot_camera_hydro <- function(cam, data, var, ylab, prefix) {
  df <- data[data$Camera == cam,]
  df <- df[order(df$WY),]
  if (nrow(df) == 0) {
    message("No seasonal data for camera ", cam)
    return(invisible(NULL))
  }

  par(mfrow = c(4, 3), mar = c(4, 5, 1, 1), oma = c(4, 4, 5, 1), cex.axis = 1.0, cex.lab = 1.1, cex.main = 1.1, mgp = c(2.5, 0.7, 0))

  for (s in 1:4) {
    subset <- df[df$Season == s,]

    plot(subset$WY, subset[[var]],
         pch = 19, col = "black", cex = 1.1,
         xlab = ifelse(s == 4, "WY", ""), ylab = ylab, # share axes
         xaxt = ifelse(s == 4, "s", "n"), yaxt = "s",
         ylim = if (var == "FP") c(0, 1) else NULL,
         bty = "l",
         main = "", font.main = 1, lwd = 1.5)
    if (s != 4) axis(1, labels = F)
    if (nrow(subset) >= 4) {
      cp_mean <- tryCatch(
        cpt.mean(subset[[var]], method = "PELT", minseglen = 6),
        error = function(e) NULL
      )
      if (!is.null(cp_mean) && length(cpts(cp_mean)) > 0) {
        segments_idx <- c(0, cpts(cp_mean), nrow(subset))
        means <- sapply(1:(length(segments_idx) - 1), function(i) {
          start <- segments_idx[i] + 1
          end <- segments_idx[i + 1]
          mean(subset[[var]][start:end], na.rm = T)
        })
        sp <- data.frame(
          x = subset$WY[head(segments_idx, -1) + 1],
          xend = subset$WY[tail(segments_idx, -1)],
          y = means,
          yend = means
        )
        segments(sp$x, sp$y, sp$xend, sp$yend, col = "red", lwd = 2)
      } else { # plots overall mean if no change points available
        overall_mean <- mean(subset[[var]], na.rm = T)
        segments(min(subset$WY), overall_mean, max(subset$WY), overall_mean, col = "red", lwd = 2)
      }
    }
    if (s == 1) {
      mtext("Mean", side = 3, line = 0.5, outer = FALSE, at = mean(par("usr")[1:2]), cex = 1.2)
    }
    mtext(labels[s], side = 2, line = 4.5, at = mean(par("usr")[3:4]), cex = 1.2)

    plot(subset$WY, subset[[var]],
         pch = 19, col = "black", cex = 1.0,
         xlab = ifelse(s == 4, "WY", ""), ylab = "",
         xaxt = ifelse(s == 4, "s", "n"), yaxt = "n",
         ylim = if (var == "FP") c(0, 1) else NULL,
         bty = "l",
         main = "", font.main = 1)
    if (s != 4) axis(1, labels = FALSE)
    axis(2, labels = FALSE)
    if (nrow(subset) >= 4) {
      cp_var <- tryCatch(
        cpt.var(subset[[var]], method = "PELT", penalty = "AIC"),
        error = function(e) NULL
      )
      if (!is.null(cp_var) && length(cpts(cp_var)) > 0) {
        segments_idx <- c(1, cpts(cp_var) + 1, nrow(subset) + 1)
        for (i in 1:(length(segments_idx) - 1)) {
          j <- segments_idx[i]:(segments_idx[i + 1] - 1)
          left <- subset$WY[segments_idx[i]]
          right <- subset$WY[segments_idx[i + 1] - 1]
          sm <- mean(subset[[var]][j], na.rm = T)
          ssd <- sd(subset[[var]][j], na.rm = T)
          bottom <- sm - ssd
          top <- sm + ssd
          rect(left, bottom,
               right, top,
               col = adjustcolor("skyblue", alpha.f = 0.3),
               border = NA)
        }
      } else {
        sm <- mean(subset[[var]], na.rm = T)
        ssd <- sd(subset[[var]], na.rm = T)
        rect(min(subset$WY), sm - ssd, max(subset$WY), sm + ssd,
             col = adjustcolor("skyblue", alpha.f = 0.3), border = NA)
      }
    }
    if (s == 1) {
      mtext("Variance", side = 3, line = 0.5, outer = FALSE, at = mean(par("usr")[1:2]), cex = 1.2)
    }

    plot(subset$WY, subset[[var]],
         pch = 19, col = "black", cex = 1.0,
         xlab = ifelse(s == 4, "WY", ""), ylab = "",
         xaxt = ifelse(s == 4, "s", "n"), yaxt = "n",
         ylim = if (var == "FP") c(0, 1) else NULL,
         bty = "l",
         main = "", font.main = 1)
    if (s != 4) axis(1, labels = FALSE)
    axis(2, labels = FALSE)
    if (nrow(subset) >= 4) {
      matrix_reg <- cbind(subset[[var]], 1, subset$WY)
      cp_reg <- tryCatch(
        cpt.reg(matrix_reg, method = "PELT"),
        error = function(e) NULL
      )
      if (!is.null(cp_reg) && length(cpts(cp_reg)) > 0) {
        segments_idx <- c(0, cpts(cp_reg), nrow(subset))
        params <- param.est(cp_reg)
        colors <- rainbow(max(1, length(segments_idx) - 1))
        for (i in 1:length(colors)) {
          idx <- (segments_idx[i] + 1):segments_idx[i + 1]
          intercept <- params$beta[i, 1]
          slope <- params$beta[i, 2]
          fitted <- intercept + slope * subset$WY[idx]
          lines(subset$WY[idx], fitted, col = colors[i], lwd = 2)
        }
      } else {
        valid_idx <- !is.na(subset[[var]])
        if (sum(valid_idx) >= 2) {
          fit <- lm(subset[[var]][valid_idx] ~ subset$WY[valid_idx])
          pred <- fitted(fit)
          lines(subset$WY[valid_idx], pred, col = "red", lwd = 2)
        }
      }
    }
    if (s == 1) {
      mtext("Regression", side = 3, line = 0.5, outer = FALSE, at = mean(par("usr")[1:2]), cex = 1.2)
    }
  }

  mtext(paste("Camera", cam, prefix, "Seasonal Change Points"), side = 3, outer = TRUE, line = 3, cex = 1.5)
}
```

```{r plots, include = F}
info <- list(
  precip = list(label = "Precipitation (mm)", title = "Precipitation"),
  vpd = list(label = "Vapor Pressure Deficit (kPa)", title = "Vapor Pressure Deficit"),
  temp = list(label = "Temperature (°C)", title = "Temperature"),
  FP = list(label = "Flow Probability", title = "FP")
)

for (cam in sort(unique(seasonal_hydro$Camera))) {
  for (var in names(info)) {
    prefix <- if (var == "FP") {
      "fp_cpd"
    } else {
      paste0(tolower(var), "_cpd")
    }
    png(sprintf("../Figures/Exhaustive/%s_c%01d.png", prefix, cam), width = 2100, height = 1800, res = 150)
    plot_camera_hydro(cam, seasonal_hydro, var, info[[var]]$label, info[[var]]$title)
    dev.off()
  }
}
```

```{r display, fig.show = 'hold', fig.width = 14, fig.height = 12, warning = F, message = F}
info <- list(
  precip = list(label = "Precipitation (mm)", title = "Precipitation"),
  vpd = list(label = "Vapor Pressure Deficit (kPa)", title = "Vapor Pressure Deficit"),
  temp = list(label = "Temperature (°C)", title = "Temperature"),
  FP = list(label = "Flow Probability", title = "FP")
)
for (cam in sort(unique(seasonal_hydro$Camera))) {
  for (var in names(info)) {
    plot_camera_hydro(cam, seasonal_hydro, var, info[[var]]$label, info[[var]]$title)
  }
}
```
