---
title: "Shallow Groundwater"
author: "Tiffany Le"
date: "2026-06-11"
output: pdf_document
---

```{r setup, warning = F, message = F}
library(dplyr)

water_year <- function(date) {
  y <- as.numeric(format(date, "%Y"))
  m <- as.numeric(format(date, "%m"))
  ifelse(m >= 10, y + 1, y)
}

season <- function(month) {
  if (month %in% c(12, 1, 2, 3)) return(1)
  else if (month %in% c(4, 5, 6)) return(2)
  else if (month %in% c(7, 8, 9)) return(3)
  else if (month %in% c(10, 11)) return(4)
}

cameras <- data.frame(
  Site = c(
    "Boquillas",
    "CharlestonMesquite",
    "Contention",
    "Fairbank",
    "Hereford",
    "Hunter",
    "Moson",
    "St.David"
  ),
  Camera = c(8, 2, 6, 1, 5, 4, 3, 7)
)
```

```{r et, warning = F, message = F}
points <- read.csv("../Data/pts_for_Jawad.csv")[1:8,]
points$Name <- gsub(" Camera", "", points$Name)
points$Index <- seq_len(nrow(points))

jawad <- do.call(rbind, lapply(points$Index, function(i) {
  file <- paste0("../Data/Jawad_ET/J", i, ".csv")
  et <- read.csv(file)
  et$Site <- points$Name[i]
  et
}))

jawad <- merge(jawad, cameras, by = "Site")
jawad$date <- as.Date(jawad$date)
jawad$ET <- jawad$LE_model * 0.0353
jawad$WY <- water_year(jawad$date)
jawad$Season <- sapply(as.integer(format(jawad$date, "%m")), season)
jawad <- jawad[order(jawad$Camera, jawad$date),]
```

```{r gw, warning = F, message = F}
gw <- read.csv("../Data/ShallowGW2006_2025.csv")
gw$lev_timestamp <- as.Date(gw$lev_timestamp, format = "%m/%d/%Y")
gw <- gw %>%
  filter(site_tp_cd == "GW", parameter_cd == "72019") %>%
  select(site_no, station_nm, lev_timestamp, lev_va, x, y) %>%
  arrange(lev_timestamp)
gw$WY <- water_year(gw$lev_timestamp)
gw$Season <- sapply(as.integer(format(gw$lev_timestamp, "%m")), season)
```

```{r merge, warning = F, message = F}
mapping <- read.csv("../Data/CamNearest3GWGage.csv")
names(mapping)[2] <- "Camera"
et <- jawad %>%
  left_join(mapping, by = "Camera") %>%
  left_join(gw, by = c("station" = "station_nm", "WY", "Season")) %>%
  group_by(Camera, WY, Season) %>%
  summarise(dtgw = mean(lev_va, na.rm = T), ET = sum(ET, na.rm = T), .groups = "drop")
```

```{r}
dry <- et[et$Season == 2,]

dry_lm <- lm(dtgw ~ ET, data = dry)
summary(dry_lm)
```

```{r}
cor(dry$dtgw, dry$ET, use = "complete.obs")
```

Inverse proportionality unexpected.
```{r}
early_dry <- dry[dry$WY <= 2014,]
late_dry <- dry[dry$WY > 2014,]

early_dry_lm <- lm(dtgw ~ ET, data = early_dry)
summary(early_dry_lm)
```

```{r}
cor(early_dry$dtgw, early_dry$ET, use = "complete.obs")
```

```{r}
late_dry_lm <- lm(dtgw ~ ET, data = late_dry)
summary(late_dry_lm)
```

```{r}
cor(late_dry$dtgw, late_dry$ET, use = "complete.obs")
```

```{r}
plot(dtgw ~ ET, data = dry)
```

```{r}
plot(dtgw ~ WY, data = dry)
```

```{r}
cagg <- et %>%
  group_by(WY, Season) %>%
  summarise(dtgw = mean(dtgw, na.rm = T), ET = sum(ET, na.rm = T), .groups = "drop")
```

```{r}
cdry <- cagg[cagg$Season == 2,]

cdry_lm <- lm(dtgw ~ ET, data = cdry)
summary(cdry_lm)
```

```{r}
cor(cdry$dtgw, cdry$ET, use = "complete.obs")
```

```{r}
early_cdry <- cdry[cdry$WY <= 2014,]
late_cdry <- cdry[cdry$WY > 2014,]

early_cdry_lm <- lm(dtgw ~ ET, data = early_cdry)
summary(early_cdry_lm)
```

```{r}
late_cdry_lm <- lm(dtgw ~ ET, data = late_cdry)
summary(late_cdry_lm)
```

```{r}
plot(dtgw ~ ET, data = cdry)
```

```{r}
plot(dtgw ~ ET, data = late_cdry)
```

```{r}
plot(dtgw ~ WY, data = cdry)
```

```{r, warning = F}
et_raw <- jawad %>%
  left_join(mapping, by = "Camera") %>%
  left_join(gw, by = c("station" = "station_nm", "WY", "Season"))

par(mfrow = c(1, 3), pin = c(2, 1.5))
for (c in 1:8) {
  for (s in unique(et_raw$station)) {
    df <- et_raw[(et_raw$station == s) & (et_raw$Camera == c),]
    if (nrow(df) == 0 || all(is.na(df$lev_va))) next
    plot(lev_va ~ lev_timestamp, data = df, main = paste("Camera", c, s))
  }
}
```

```{r, warning = F}
sig <- c("D-20-21 10AAC2 [FBK-UP]", "D-20-21 15DDB [BOQ-UP]", "D-21-21 13BAB1 [MOSLNS]", "D-22-22 33BBC [HUN-UP]", "D-23-22 04DCD4 [HERUED]", "D-19-21 28ACD [TOM-LI]", "D-19-21 05AAA1 [STD-LI]", "D-20-21 15DBD1 [BOQ-LI]")

single <- jawad %>%
  left_join(mapping, by = "Camera") %>%
  left_join(gw, by = c("station" = "station_nm", "WY", "Season")) %>%
  filter(
    station %in% sig,
    !(Camera == 8 & station == "D-20-21 15DDB [BOQ-UP]")
  ) %>%
  filter(Camera == 8) %>%
  group_by(WY, Season) %>%
  summarise(lev_va = mean(lev_va, na.rm = T), ET = sum(ET, na.rm = T), .groups = "drop")
```


```{r}
sdry <- single[single$Season == 2,]

sdry_lm <- lm(lev_va ~ ET, data = sdry)
summary(sdry_lm)
```

```{r}
cor(sdry$lev_va, sdry$ET, use = "complete.obs")
```

```{r}
early_sdry <- sdry[sdry$WY <= 2014,]
late_sdry <- sdry[sdry$WY > 2014,]

early_sdry_lm <- lm(lev_va ~ ET, data = early_sdry)
summary(early_sdry_lm)
```

```{r}
cor(early_sdry$lev_va, early_sdry$ET, use = "complete.obs")
```

```{r}
late_sdry_lm <- lm(lev_va ~ ET, data = late_sdry)
summary(late_sdry_lm)
```

```{r}
cor(late_sdry$lev_va, late_sdry$ET, use = "complete.obs")
```
```{r}
plot(lev_va ~ ET, data = sdry)
```

```{r}
plot(lev_va ~ WY, data = sdry)
```

7: NA
6: NA
1: NA
8: WP
2: NA
3: SN
4: SN < 2014
5: N

No significant changes at 4 highly correlated sites. DTGW and ET have the strongest relationship at sites where streamflow is perennial.

```{r}
single_raw <- jawad %>%
  left_join(mapping, by = "Camera") %>%
  left_join(gw, by = c("station" = "station_nm", "WY", "Season")) %>%
  filter(
    station %in% sig,
    !(Camera == 8 & station == "D-20-21 15DDB [BOQ-UP]")
  ) %>%
  select(Site, Camera, station, date, ET, lev_va, WY, Season, latitude, longitude, geometry, dist)
```

```{r}
write.csv(single_raw, "../Data/CamShallowGW2006_2025.csv")
```

